### ISSUE TITLE
__getitem__(name) KeyError

### ISSUE THREAD

**Issue by ivanistheone** [mdipierro/workflow#3]
in

https://github.com/mdipierro/workflow/blob/master/workflow.py#L90

```
                    data[name] = data[name]+[key]
```

should be 

```
                    if data.has_key(name):
                        data[name] = data[name]+[key]
                    else:
                        data[name] = [key]
```

I know it sucks to have to add an extra line of code, but on the + side it will work :)

fixes this issue 

05-31 18:17: INFO    : idea.tex -> pdflatex idea.tex 
{'*.tex=idea.tex:pdflatex $0': 1338502637.0}
pdftex
Traceback (most recent call last):
  File "./workflow.py", line 135, in <module>
    if **name**=='**main**': main()
  File "./workflow.py", line 133, in main
    workflow(options)
  File "./workflow.py", line 93, in workflow
    data[name] = data[name]+[key]
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shelve.py", line 121, in **getitem**
    f = StringIO(self.dict[key])
KeyError: 'pdftex'

**Comment by mdipierro** [comment]
Hello Ivan,

there is an easier solution

data[name] = data.get(name,[])+[key]

but it should not be necessary because of line 39:

```
        if not name in data:
            data[name]=[]
```

Can you help me debug and understand why this happens?

**Comment by ivanistheone** [comment]
```
    if not name in data:
        data[name]=[]
```

you mean this 
https://github.com/mdipierro/workflow/blob/master/workflow.py#L38 ?

in that context ''data'' is data = open(config_filename,'r').read() and not
data = shelve.open(cache_filename)

**Comment by mdipierro** [comment]
oops. That's the bug then. Please check if the fix in trunk fixes the issue. Thanks for reporting the issue.

**Comment by ivanistheone** [comment]
works.
nice.

**Comment by mdipierro** [comment]
thanks for the report and for checking
